name: flutter_device_emulator_example
description: Example app for flutter_device_emulator
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_device_emulator:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/image/