name: flutter_device_emulator
description: "Preview your Flutter widgets across multiple device screens in real-time."
version: 0.0.3
homepage: https://github.com/ravi84184/flutter_device_emulator
repository: https://github.com/ravi84184/flutter_device_emulator

environment:
  sdk: ^3.8.1
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  device_frame: ^1.4.0
  web: ^1.1.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

