name: flutter_device_emulator
description: "Preview your Flutter widgets across multiple device screens in real-time. Supports iPhone, Pixel, tablet, and foldable layouts with toggles for dark/light themes, text directions (LTR/RTL), and orientation (portrait/landscape). Ideal for building responsive and internationalized UIs quickly."
version: 0.0.2
homepage: https://github.com/ravi84184/flutter_device_emulator
repository: https://github.com/ravi84184/flutter_device_emulator

environment:
  sdk: ^3.8.1
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  screenshot: ^1.3.0
  device_frame: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

platforms:
  web:
